# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 14 Jun 2022 05:40:23 +0000
*               @ALL          1
*               @user         8
