<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Tue, 14 Jun 2022 05:40:23 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
