# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 14 Jun 2022 05:40:23 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$K8LMqJ55jqMmdoJL3Kl1jujKgjITrlFVhOH2g7.G.z/v9/OotbIbG:admin:2439158248@qq.com:admin,user
